-- CreateTable
CREATE TABLE `tb_test_user` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NULL,

    UNIQUE INDEX `tb_test_user_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_test_post` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `content` VARCHAR(191) NULL,
    `published` BOOLEAN NULL DEFAULT false,
    `authorId` INTEGER NULL,

    INDEX `tb_test_post_authorId_fkey`(`authorId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `mtb_shop_manage` (
    `MS_NO` VARCHAR(10) NOT NULL,
    `MS_NM` VARCHAR(100) NOT NULL,
    `MS_ENG_NM` VARCHAR(100) NULL,
    `CHAIN_NO` VARCHAR(4) NOT NULL DEFAULT '0000',
    `CHAIN_HQ_YN` CHAR(1) NOT NULL DEFAULT 'N',
    `BIZ_NO` VARCHAR(10) NOT NULL,
    `BS_TYPE` VARCHAR(30) NOT NULL,
    `BS_KIND` VARCHAR(30) NOT NULL,
    `MASTER_NM` VARCHAR(10) NOT NULL,
    `TEL_NO` VARCHAR(15) NULL,
    `HP_NO` VARCHAR(15) NULL,
    `HOT_LINE` VARCHAR(15) NULL,
    `EMAIL` VARCHAR(30) NULL,
    `HOMEPAGE` VARCHAR(50) NULL,
    `BILL_ADDR` VARCHAR(120) NULL,
    `ZIP_NO` VARCHAR(10) NOT NULL,
    `ADDRESS` VARCHAR(120) NOT NULL,
    `ADDRESS_DETAIL` VARCHAR(120) NULL,
    `OPEN_DATE` VARCHAR(8) NULL,
    `START_DATE` VARCHAR(8) NULL,
    `CLOSE_DATE` VARCHAR(8) NULL,
    `OPEN_FG` CHAR(1) NOT NULL DEFAULT '1',
    `LANG_FG` VARCHAR(3) NOT NULL,
    `THEMA_CD` VARCHAR(3) NOT NULL,
    `CREATE_ID` VARCHAR(20) NOT NULL,
    `CREATE_DTIME` VARCHAR(14) NOT NULL,
    `LAST_ID` VARCHAR(20) NOT NULL,
    `LAST_DTIME` VARCHAR(14) NOT NULL,

    UNIQUE INDEX `MS_NO`(`MS_NO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ctb_waiting_list` (
    `SEND_DATE` VARCHAR(8) NOT NULL,
    `MS_NO` VARCHAR(10) NOT NULL,
    `SEQ` INTEGER NOT NULL AUTO_INCREMENT,
    `HP_NO` VARCHAR(15) NULL,
    `ADULT_CNT` INTEGER NOT NULL,
    `KIDS_CNT` INTEGER NOT NULL,
    `SEND_DTIME` VARCHAR(14) NOT NULL,
    `PROC_FG` VARCHAR(15) NOT NULL,
    `CREATE_ID` VARCHAR(20) NOT NULL,
    `CREATE_DTIME` VARCHAR(14) NOT NULL,
    `LAST_ID` VARCHAR(20) NOT NULL,
    `LAST_DTIME` VARCHAR(14) NOT NULL,

    UNIQUE INDEX `SEND_DATE`(`SEND_DATE`, `MS_NO`, `SEQ`),
    PRIMARY KEY (`SEQ`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `mtb_user_manage` (
    `MS_NO` VARCHAR(10) NOT NULL,
    `USER_ID` VARCHAR(20) NOT NULL,
    `USER_NM` VARCHAR(20) NOT NULL,
    `PASSWD` VARCHAR(80) NOT NULL,
    `DEFAULT_YN` CHAR(1) NOT NULL,
    `HP_NO` VARCHAR(15) NULL,
    `HOT_LINE` VARCHAR(15) NULL,
    `EMAIL` VARCHAR(30) NULL,
    `ZIP_NO` VARCHAR(6) NULL,
    `ADDRESS` VARCHAR(60) NULL,
    `ADDRESS_DT` VARCHAR(50) NULL,
    `START_DATE` VARCHAR(8) NULL,
    `END_DATE` VARCHAR(8) NULL,
    `EMP_FG` VARCHAR(2) NOT NULL,
    `STATUS_FG` CHAR(1) NOT NULL DEFAULT '0',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y',
    `EMP_ID` VARCHAR(10) NULL,
    `CREATE_ID` VARCHAR(20) NOT NULL,
    `CREATE_DTIME` VARCHAR(14) NOT NULL,
    `LAST_ID` VARCHAR(20) NOT NULL,
    `LAST_DTIME` VARCHAR(14) NOT NULL,

    UNIQUE INDEX `MS_NO`(`MS_NO`, `USER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `tb_test_post` ADD CONSTRAINT `tb_test_post_authorId_fkey` FOREIGN KEY (`authorId`) REFERENCES `tb_test_user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
